export { default } from "./src/wallet-manager-aptos.js";
export { default as WalletAccountReadOnlyAptos } from "./src/wallet-account-read-only-aptos.js";
export { default as WalletAccountAptos } from "./src/wallet-account-aptos.js";
export type FeeRates = import("@tetherto/wdk-wallet").FeeRates;
export type KeyPair = import("@tetherto/wdk-wallet").KeyPair;
export type TransactionResult = import("@tetherto/wdk-wallet").TransactionResult;
export type TransferOptions = import("@tetherto/wdk-wallet").TransferOptions;
export type TransferResult = import("@tetherto/wdk-wallet").TransferResult;
export type Finality = import("@tetherto/wdk-wallet").Finality;
export type TransactionReceipt = import("@tetherto/wdk-wallet").TransactionReceipt;
export type WaitForTransactionTarget = import("@tetherto/wdk-wallet").WaitForTransactionTarget;
export type WaitForTransactionOptions = import("@tetherto/wdk-wallet").WaitForTransactionOptions;
export type AptosTransaction = import("./src/wallet-account-read-only-aptos.js").AptosTransaction;
export type AptosWalletConfig = import("./src/wallet-account-read-only-aptos.js").AptosWalletConfig;
export type AptosTransactionInfo = import("./src/wallet-account-read-only-aptos.js").AptosTransactionInfo;
